apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-assets-deployment
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: static-assets
  template:
    metadata:
      labels:
        app: static-assets
    spec:
      containers:
        - name: nginx-assets-container
          image: ghcr.io/tudopacu/city_builder-assets:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: static-assets-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: static-assets