name: Build and Push Static Assets

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Repository Name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Trigger Infrastructure Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_PAT }}
          repository: tudopacu/city_builder-infrastructure
          event-type: update-image
          client-payload: '{"app": "yii2-cms", "image": "ghcr.io/tudopacu/city_builder-cms:${{ github.sha }}"}'